server:
  port: 8080

spring:
  application:
    name: planvel

  servlet:
    session:
      timeout: 30m
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: application-secret.yml
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://planvel-mysql:3306/planvel_db
    username: planvel
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  upload-dir: uploads/
  default-profile-img: /uploads/profile/default_profile.png